services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - pg_data:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      TZ: Asia/Tbilisi
      N8N_PROTOCOL: http
      N8N_SECURE_COOKIE: "false"
      N8N_PUBLIC_URL: ${N8N_PUBLIC_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pg_data:
  n8n_data:
