services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http --url=tarpon-included-ultimately.ngrok-free.app 80
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    network_mode: "host"
